env_kwargs:
  agent_hz: 15
  distance_factor: 10.0
  flight_dome_size: 32.0
  formation_center:
  - -1.4116513132744366
  - -3.385256728008814
  - 4.28770460209851
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 300.0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 10.0
    lm_spawn_radius: 10.0
    lw_center_bounds: 10.0
    lw_spawn_radius: 2.0
    min_z: 0.5
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - 0.32730506256721825
    - 0.22620337745919628
    - 4.568333158592549
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 4.966911723709636
    - -13.662205019571296
    - 3.4058360702330925
  - - 0.5883486867255634
    - -3.385256728008814
    - 4.28770460209851
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.98
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
