env_kwargs:
  agent_hz: 30
  distance_factor: 3.0
  flight_dome_size: 27.0
  formation_center:
  - -1.9399389997396455
  - 3.6834978895900576
  - 5.546147963753039
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 500.0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 10.0
    lm_spawn_radius: 10.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - -0.8993624700791893
    - 0.9491260244396618
    - -6.158802925826877
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 3.692087869760277
    - 14.282277274713053
    - 5.384296198777851
  - - 0.06006100026035455
    - 3.6834978895900576
    - 5.546147963753039
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 256
  num_vec_envs: 32
