env_kwargs:
  agent_hz: 30
  distance_factor: 3.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -4.40000191120512
  - -0.033236751654955654
  - 1.9189019192355778
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 2
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.0
  start_orn:
  - - -0.9007336825656478
    - -0.8594187719093827
    - -3.6355123412155415
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 2.493580166751583
    - -5.14152061574877
    - 4.186180262636647
  - - -2.40000191120512
    - -0.033236751654955654
    - 1.9189019192355778
  thrust_limit: 10.0
spawn_settings: *id001
train_kwargs:
  batch_size: 128
  device: cpu
  discount_factor: 0.99
  lr: 0.0001
  nn_t:
  - 256
  - 256
  - 512
  num_vec_envs: 8
