env_kwargs:
  agent_hz: 30
  distance_factor: 30.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -1.7104915042804683
  - -4.6591029129743475
  - 1.0838940769997691
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 3
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - 0.15946205583711448
    - 0.5169882600353923
    - -5.5051963156675905
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 4.486950408605412
    - -3.243112126453327
    - 8.786744480916486
  - - 0.28950849571953174
    - -4.6591029129743475
    - 1.0838940769997691
  thrust_limit: 0.9
spawn_settings: *id001
train_kwargs:
  batch_size: 2048
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
