env_kwargs:
  agent_hz: 30
  distance_factor: 1.0
  flight_dome_size: 27.0
  formation_center:
  - 0.606144410758997
  - -1.8941144284253566
  - 1.00881453230413
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 1.0
  rew_exploding_target: 500.0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 10.0
    lm_spawn_radius: 10.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - 0.20934355807599192
    - 0.3610000986809776
    - -3.2208370736504515
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - -11.668812856861814
    - 3.6636969385028912
    - 12.699081149267023
  - - 2.606144410758997
    - -1.8941144284253566
    - 1.00881453230413
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 256
  num_vec_envs: 64
