env_kwargs:
  agent_hz: 30
  distance_factor: 3.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -1.3137587729372822
  - 0.639951212684382
  - 2.8163264308911806
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10.0
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 2
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.0
  start_orn:
  - - -0.10340756178431532
    - 0.5460981552736086
    - 1.1513101513631185
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 1.4549828726055045
    - 7.683974842071187
    - 5.286957919346915
  - - 0.6862412270627178
    - 0.639951212684382
    - 2.8163264308911806
  thrust_limit: 10.0
spawn_settings: *id001
train_kwargs:
  batch_size: 256
  device: cpu
  discount_factor: 0.99
  lr: 0.0001
  nn_t:
  - 256
  - 256
  - 512
  num_vec_envs: 8
