env_kwargs:
  agent_hz: 15
  distance_factor: 1.0
  flight_dome_size: 32.0
  formation_center:
  - -6.200270403971406
  - -1.5109166476039082
  - 3.105037386771023
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 300.0
  save_step_data: True
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 10.0
    lm_spawn_radius: 10.0
    lw_center_bounds: 10.0
    lw_spawn_radius: 2.0
    min_z: 0.5
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 1.0
  start_orn:
  - - 0.026473211385562134
    - -0.8891549671747221
    - 5.056889062646611
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - -12.688958914488492
    - 11.800236192867953
    - 11.325072476350638
  - - -4.200270403971406
    - -1.5109166476039082
    - 3.105037386771023
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.98
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
