env_kwargs:
  agent_hz: 30
  distance_factor: 30.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -2.7147079981036493
  - -1.074622550943647
  - 1.7392648286693455
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 3
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - 0.07461158169570759
    - -0.41292244277504975
    - 5.040666455103881
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 0.3513066947683905
    - 0.24211583161331962
    - 4.840913464166993
  - - -0.7147079981036493
    - -1.074622550943647
    - 1.7392648286693455
  thrust_limit: 0.8
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 256
  - 256
  num_vec_envs: 16
