env_kwargs:
  agent_hz: 30
  distance_factor: 1.0
  flight_dome_size: 27.0
  formation_center:
  - 1.3859864981126453
  - -1.314429480841115
  - 1.4657057763438444
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 500.0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 10.0
    lm_spawn_radius: 10.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - 0.28301900255881995
    - 0.7176297004822931
    - 0.37251877706869435
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - -0.05800624246858632
    - 6.643165095631826
    - 6.446291639644292
  - - 3.3859864981126453
    - -1.314429480841115
    - 1.4657057763438444
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 256
  num_vec_envs: 64
