env_kwargs:
  agent_hz: 30
  distance_factor: 30.0
  flight_dome_size: 17.0
  formation_center:
  - -2.605952863249783
  - -0.7819910872774161
  - 2.361852483653257
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 200.0
  reward_type: 0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 1.0
  start_orn:
  - - 0.3750928695436657
    - -0.29168772359715134
    - -5.915239827330792
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 4.53042889960819
    - 1.7340450720029912
    - 2.4873391126474327
  - - -0.605952863249783
    - -0.7819910872774161
    - 2.361852483653257
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.98
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
