env_kwargs:
  agent_hz: 30
  distance_factor: 6.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - 0.6282571222809255
  - 2.7554754347964137
  - 1.7310560397817416
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 200.0
  reward_type: 3
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.0
  start_orn:
  - - 0.5220629277703217
    - 0.6277938698447585
    - 0.13887818304125504
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 2.3137550983079684
    - 2.086084687902331
    - 9.609420488995605
  - - 2.6282571222809255
    - 2.7554754347964137
    - 1.7310560397817416
  thrust_limit: 10.0
spawn_settings: *id001
train_kwargs:
  batch_size: 128
  device: cpu
  discount_factor: 0.99
  lr: 0.0001
  nn_t:
  - 256
  - 256
  - 512
  num_vec_envs: 8
