env_kwargs:
  agent_hz: 30
  distance_factor: 30.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -4.284825655216072
  - 3.3306968323689627
  - 1.2001858530263219
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 3
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.4
  start_orn:
  - - -0.9744343034691043
    - -0.964524887671387
    - 6.275405953804062
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - 0.7413038435016173
    - -1.5034663852732306
    - 1.2141463578542298
  - - -2.284825655216072
    - 3.3306968323689627
    - 1.2001858530263219
  thrust_limit: 10.0
spawn_settings: *id001
train_kwargs:
  batch_size: 2048
  device: cuda
  discount_factor: 0.99
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
