env_kwargs:
  agent_hz: 30
  distance_factor: 3.0
  explosion_radius: 0.5
  flight_dome_size: 17.0
  formation_center:
  - -4.937293014523747
  - -1.1103476664939094
  - 1.6466223079895395
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 10
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.1
  rew_exploding_target: 100.0
  reward_type: 3
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.1
  start_orn:
  - - -0.16228165611107825
    - -0.04847645811067047
    - 1.5943477312938505
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - -3.581939346723191
    - -2.8850602155847724
    - 8.144627104457918
  - - -2.937293014523747
    - -1.1103476664939094
    - 1.6466223079895395
  thrust_limit: 10.0
spawn_settings: *id001
train_kwargs:
  batch_size: 1024
  device: cpu
  discount_factor: 0.99
  lr: 1.0e-05
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 8
