env_kwargs:
  agent_hz: 30
  distance_factor: 30.0
  flight_dome_size: 17.0
  formation_center:
  - -2.7869836398351557
  - 2.471689892827559
  - 2.997781261096958
  lethal_angle: 0.15
  lethal_distance: 3.0
  lw_attacks: false
  lw_chases: false
  lw_moves_random: false
  lw_shoot_range: 1.0
  lw_stand_still: true
  lw_threat_radius: 4.0
  max_duration_seconds: 15
  max_velocity_magnitude: 10.0
  num_lm: 1
  num_lw: 1
  proximity_factor: 0.2
  rew_exploding_target: 200.0
  save_step_data: false
  seed: null
  spawn_settings: &id001
    lm_center_bounds: 5.0
    lm_spawn_radius: 5.0
    lw_center_bounds: 5.0
    lw_spawn_radius: 2.0
    min_z: 1
    num_lm: 1
    num_lw: 1
    seed: null
  speed_factor: 0.3
  start_orn:
  - - -0.6815957943914188
    - -0.7491744661653854
    - 1.6890497253477212
  - - 0.0
    - 0.0
    - 0.0
  start_pos:
  - - -8.329251314293472
    - 8.405581749348741
    - 1.4974093898745418
  - - -0.7869836398351557
    - 2.471689892827559
    - 2.997781261096958
spawn_settings: *id001
train_kwargs:
  batch_size: 512
  device: cuda
  discount_factor: 0.98
  lr: 0.001
  nn_t:
  - 128
  - 128
  - 128
  num_vec_envs: 16
